#include "motion_driver.h"
#include "main.h" // For HAL_TIM_HandleTypeDef, etc.
#include "app_config.h"

#include <stdbool.h>

// --- External HAL Handles (from main.c, generated by CubeMX) ---
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;

// --- Pin Mapping Arrays ---
// These arrays map a motor_id (0-7) to its specific GPIO Port/Pin and Timer/Channel

//--------------Directions--------------//

// Pointers to GPIO_TypeDef for Direction pins
static GPIO_TypeDef* MotorDirPorts[MOTOR_COUNT] = {
    GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB
};

// Pin numbers for Direction pins
static uint16_t MotorDirPins[MOTOR_COUNT] = {
    GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3,
    GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_12, GPIO_PIN_13
};

//--------------Enables--------------//

// Pointers to GPIO_TypeDef for Enable pins
static GPIO_TypeDef* MotorEnPorts[MOTOR_COUNT] = {
    GPIOA, GPIOA, GPIOA, GPIOA, GPIOA, GPIOA, GPIOB, GPIOB
};

// Pin numbers for Enable pins
static uint16_t MotorEnPins[MOTOR_COUNT] = {
    GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7,
    GPIO_PIN_12, GPIO_PIN_15, GPIO_PIN_14, GPIO_PIN_15
};

//--------------Steps--------------//

// Pointers to TIM_HandleTypeDef for Step PWM
static TIM_HandleTypeDef* MotorStepTimHandles[MOTOR_COUNT] = {
    &htim1, &htim1, &htim1, &htim1,
    &htim2, &htim2, &htim2, &htim2
};

// Channel numbers for Step PWM
static uint32_t MotorStepTimChannels[MOTOR_COUNT] = {
    TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4,
    TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4
};

static volatile bool s_finite_active[MOTOR_COUNT];
static volatile uint32_t s_remaining_steps[MOTOR_COUNT];
static volatile uint32_t s_completed_motor_mask;

static void MotionDriver_DisableTimerOutputs(TIM_TypeDef *tim, bool has_main_output_enable)
{
    tim->CCER &= (uint16_t)~(TIM_CCER_CC1E | TIM_CCER_CC2E | TIM_CCER_CC3E | TIM_CCER_CC4E);
    tim->CR1 &= (uint16_t)~TIM_CR1_CEN;

    if (has_main_output_enable) {
        tim->BDTR &= (uint16_t)~TIM_BDTR_MOE;
    }
}

static uint8_t MotionDriver_FindMotorByTimerAndActiveChannel(TIM_HandleTypeDef *htim)
{
    uint32_t channel;

    if (htim == NULL) {
        return MOTOR_ID_INVALID;
    }

    switch (htim->Channel) {
    case HAL_TIM_ACTIVE_CHANNEL_1:
        channel = TIM_CHANNEL_1;
        break;
    case HAL_TIM_ACTIVE_CHANNEL_2:
        channel = TIM_CHANNEL_2;
        break;
    case HAL_TIM_ACTIVE_CHANNEL_3:
        channel = TIM_CHANNEL_3;
        break;
    case HAL_TIM_ACTIVE_CHANNEL_4:
        channel = TIM_CHANNEL_4;
        break;
    default:
        return MOTOR_ID_INVALID;
    }

    for (uint8_t i = 0; i < MOTOR_COUNT; i++) {
        if (MotorStepTimHandles[i]->Instance == htim->Instance &&
            MotorStepTimChannels[i] == channel) {
            return i;
        }
    }

    return MOTOR_ID_INVALID;
}

static bool MotionDriver_ConfigurePwm(uint8_t motor_id, uint32_t frequency)
{
    if (motor_id >= MOTOR_COUNT || frequency == 0U) {
        return false;
    }

    TIM_HandleTypeDef* htim = MotorStepTimHandles[motor_id];
    uint32_t channel = MotorStepTimChannels[motor_id];
    uint32_t timerClock = 64000000U;
    uint32_t calculatedARR = 0U;
    uint32_t currentPrescaler;

    // Подбираем PSC/ARR под requested STEP frequency и 16-bit ARR.
    for (currentPrescaler = 1U; currentPrescaler <= 65536U; currentPrescaler++) {
        calculatedARR = (timerClock / currentPrescaler / frequency) - 1U;
        if (calculatedARR > 0U && calculatedARR <= 65535U) {
            break;
        }
    }

    if (currentPrescaler > 65536U || calculatedARR == 0U) {
        return false;
    }

    htim->Instance->PSC = currentPrescaler - 1U;
    htim->Instance->ARR = calculatedARR;
    __HAL_TIM_SET_COMPARE(htim, channel, (calculatedARR + 1U) / 2U);

    // Немедленно загружаем новые PSC/ARR перед стартом PWM.
    htim->Instance->EGR = TIM_EGR_UG;

    return true;
}

static void MotionDriver_StopPwmChannel(uint8_t motor_id, bool finite_mode)
{
    TIM_HandleTypeDef* htim = MotorStepTimHandles[motor_id];
    uint32_t channel = MotorStepTimChannels[motor_id];

    if (finite_mode) {
        (void)HAL_TIM_PWM_Stop_IT(htim, channel);
    } else {
        (void)HAL_TIM_PWM_Stop(htim, channel);
    }

    // EN active low: переводим драйвер в idle/disabled после остановки STEP.
    HAL_GPIO_WritePin(MotorEnPorts[motor_id], MotorEnPins[motor_id], GPIO_PIN_SET);
}

// --- Function Implementations ---

/**
 * @brief Initializes the Motion Driver, typically disabling all motors.
 */
void MotionDriver_Init(void)
{
    MotionDriver_AllSafe();
}

/**
 * @brief Forces all motion outputs into a safe state without RTOS or CAN dependencies.
 */
void MotionDriver_AllSafe(void)
{
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_TIM1_CLK_ENABLE();
    __HAL_RCC_TIM2_CLK_ENABLE();

    MotionDriver_DisableTimerOutputs(TIM1, true);
    MotionDriver_DisableTimerOutputs(TIM2, false);

    for (uint8_t i = 0; i < MOTOR_COUNT; i++) {
        s_finite_active[i] = false;
        s_remaining_steps[i] = 0U;
        HAL_GPIO_WritePin(MotorEnPorts[i], MotorEnPins[i], GPIO_PIN_SET);
    }

    s_completed_motor_mask = 0U;
}

/**
 * @brief Sets the direction of rotation for a specific motor.
 * @param motor_id ID of the motor (0-7).
 * @param forward True for forward, false for reverse.
 */
void MotionDriver_SetDirection(uint8_t motor_id, bool forward)
{
    if (motor_id >= MOTOR_COUNT) {
        return;
    }

    if (forward) {
        HAL_GPIO_WritePin(MotorDirPorts[motor_id], MotorDirPins[motor_id], GPIO_PIN_SET);
    } else {
        HAL_GPIO_WritePin(MotorDirPorts[motor_id], MotorDirPins[motor_id], GPIO_PIN_RESET);
    }
}

/**
 * @brief Starts the PWM generation for a specific motor at a given frequency.
 * @param motor_id ID of the motor (0-7).
 * @param frequency Desired step frequency in Hz.
 * @note Assumes timer clock is 64MHz. Duty cycle is fixed at 50%.
 */
void MotionDriver_StartMotor(uint8_t motor_id, uint32_t frequency)
{
    if (motor_id >= MOTOR_COUNT || frequency == 0) {
        MotionDriver_StopMotor(motor_id); // Stop if invalid input
        return;
    }

    s_finite_active[motor_id] = false;
    s_remaining_steps[motor_id] = 0U;

    if (!MotionDriver_ConfigurePwm(motor_id, frequency)) {
        MotionDriver_StopMotor(motor_id);
        return;
    }

    TIM_HandleTypeDef* htim = MotorStepTimHandles[motor_id];
    uint32_t channel = MotorStepTimChannels[motor_id];
    HAL_GPIO_WritePin(MotorEnPorts[motor_id], MotorEnPins[motor_id], GPIO_PIN_RESET);
    HAL_TIM_PWM_Start(htim, channel);
}

bool MotionDriver_StartFinite(uint8_t motor_id, uint32_t frequency, uint32_t steps)
{
    if (motor_id >= MOTOR_COUNT || frequency == 0U || steps == 0U) {
        return false;
    }

    if (!MotionDriver_ConfigurePwm(motor_id, frequency)) {
        MotionDriver_StopMotor(motor_id);
        return false;
    }

    TIM_HandleTypeDef* htim = MotorStepTimHandles[motor_id];
    uint32_t channel = MotorStepTimChannels[motor_id];

    s_completed_motor_mask &= ~(1UL << motor_id);
    s_remaining_steps[motor_id] = steps;
    s_finite_active[motor_id] = true;

    // EN active low: нагрузку включаем только после успешной настройки PWM.
    HAL_GPIO_WritePin(MotorEnPorts[motor_id], MotorEnPins[motor_id], GPIO_PIN_RESET);

    if (HAL_TIM_PWM_Start_IT(htim, channel) != HAL_OK) {
        s_finite_active[motor_id] = false;
        s_remaining_steps[motor_id] = 0U;
        MotionDriver_StopMotor(motor_id);
        return false;
    }

    return true;
}

/**
 * @brief Stops the PWM generation for a specific motor and disables its driver.
 * @param motor_id ID of the motor (0-7).
 */
void MotionDriver_StopMotor(uint8_t motor_id)
{
    if (motor_id >= MOTOR_COUNT) {
        return;
    }

    bool finite_mode = s_finite_active[motor_id];
    s_finite_active[motor_id] = false;
    s_remaining_steps[motor_id] = 0U;
    s_completed_motor_mask &= ~(1UL << motor_id);

    MotionDriver_StopPwmChannel(motor_id, finite_mode);
}

bool MotionDriver_ConsumeCompletedMotor(uint8_t *motor_id)
{
    if (motor_id == NULL) {
        return false;
    }

    __disable_irq();
    uint32_t mask = s_completed_motor_mask;
    if (mask == 0U) {
        __enable_irq();
        return false;
    }

    for (uint8_t i = 0; i < MOTOR_COUNT; i++) {
        if ((mask & (1UL << i)) != 0U) {
            s_completed_motor_mask &= ~(1UL << i);
            __enable_irq();
            *motor_id = i;
            return true;
        }
    }

    __enable_irq();
    return false;
}

void HAL_TIM_PWM_PulseFinishedCallback(TIM_HandleTypeDef *htim)
{
    uint8_t motor_id = MotionDriver_FindMotorByTimerAndActiveChannel(htim);

    if (motor_id >= MOTOR_COUNT || !s_finite_active[motor_id]) {
        return;
    }

    if (s_remaining_steps[motor_id] > 0U) {
        s_remaining_steps[motor_id]--;
    }

    if (s_remaining_steps[motor_id] == 0U) {
        // ISR-контекст: только останавливаем STEP и ставим completion flag.
        // CAN DONE отправит MotionController из task context.
        s_finite_active[motor_id] = false;
        MotionDriver_StopPwmChannel(motor_id, true);
        s_completed_motor_mask |= (1UL << motor_id);
    }
}
