#include "motion_driver.h"
#include "main.h" // For HAL_TIM_HandleTypeDef, etc.
#include "app_config.h"

#include <stdbool.h>

// --- External HAL Handles (from main.c, generated by CubeMX) ---
extern TIM_HandleTypeDef htim1;
extern TIM_HandleTypeDef htim2;

// --- Pin Mapping Arrays ---
// These arrays map a motor_id (0-7) to its specific GPIO Port/Pin and Timer/Channel

//--------------Directions--------------//

// Pointers to GPIO_TypeDef for Direction pins
static GPIO_TypeDef* MotorDirPorts[MOTOR_COUNT] = {
    GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB, GPIOB
};

// Pin numbers for Direction pins
static uint16_t MotorDirPins[MOTOR_COUNT] = {
    GPIO_PIN_0, GPIO_PIN_1, GPIO_PIN_2, GPIO_PIN_3,
    GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_12, GPIO_PIN_13
};

//--------------Enables--------------//

// Pointers to GPIO_TypeDef for Enable pins
static GPIO_TypeDef* MotorEnPorts[MOTOR_COUNT] = {
    GPIOA, GPIOA, GPIOA, GPIOA, GPIOA, GPIOA, GPIOB, GPIOB
};

// Pin numbers for Enable pins
static uint16_t MotorEnPins[MOTOR_COUNT] = {
    GPIO_PIN_4, GPIO_PIN_5, GPIO_PIN_6, GPIO_PIN_7,
    GPIO_PIN_12, GPIO_PIN_15, GPIO_PIN_14, GPIO_PIN_15
};

//--------------Steps--------------//

// Pointers to TIM_HandleTypeDef for Step PWM
static TIM_HandleTypeDef* MotorStepTimHandles[MOTOR_COUNT] = {
    &htim1, &htim1, &htim1, &htim1,
    &htim2, &htim2, &htim2, &htim2
};

// Channel numbers for Step PWM
static uint32_t MotorStepTimChannels[MOTOR_COUNT] = {
    TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4,
    TIM_CHANNEL_1, TIM_CHANNEL_2, TIM_CHANNEL_3, TIM_CHANNEL_4
};

// --- Function Implementations ---

/**
 * @brief Initializes the Motion Driver, typically disabling all motors.
 */
void MotionDriver_Init(void)
{
    // Ensure all motors are disabled on startup
    for (uint8_t i = 0; i < MOTOR_COUNT; i++) {
        MotionDriver_StopMotor(i); // This will also disable the motor
    }
}

/**
 * @brief Sets the direction of rotation for a specific motor.
 * @param motor_id ID of the motor (0-7).
 * @param forward True for forward, false for reverse.
 */
void MotionDriver_SetDirection(uint8_t motor_id, bool forward)
{
    if (motor_id >= MOTOR_COUNT) {
        return;
    }

    if (forward) {
        HAL_GPIO_WritePin(MotorDirPorts[motor_id], MotorDirPins[motor_id], GPIO_PIN_SET);
    } else {
        HAL_GPIO_WritePin(MotorDirPorts[motor_id], MotorDirPins[motor_id], GPIO_PIN_RESET);
    }
}

/**
 * @brief Starts the PWM generation for a specific motor at a given frequency.
 * @param motor_id ID of the motor (0-7).
 * @param frequency Desired step frequency in Hz.
 * @note Assumes timer clock is 64MHz. Duty cycle is fixed at 50%.
 */
void MotionDriver_StartMotor(uint8_t motor_id, uint32_t frequency)
{
    if (motor_id >= MOTOR_COUNT || frequency == 0) {
        MotionDriver_StopMotor(motor_id); // Stop if invalid input
        return;
    }

    TIM_HandleTypeDef* htim = MotorStepTimHandles[motor_id];
    uint32_t channel = MotorStepTimChannels[motor_id];

    // Enable the motor (EN is active low)
    HAL_GPIO_WritePin(MotorEnPorts[motor_id], MotorEnPins[motor_id], GPIO_PIN_RESET);

    uint32_t timerClock = 64000000; // Assuming APB1/APB2 Timer clock is 64MHz (PCLK*2 for most cases)
    uint32_t psc_reg = 0;
    uint32_t calculatedARR = 0;
    uint32_t currentPrescaler = 1; // (PSC+1)

    // Dynamically adjust prescaler to get good frequency resolution and stay within 16-bit ARR
    // Aim to keep ARR in a reasonable range, max 65535
    for (currentPrescaler = 1; currentPrescaler <= 65536; currentPrescaler++) {
        calculatedARR = (timerClock / currentPrescaler / frequency) - 1;
        if (calculatedARR > 0 && calculatedARR <= 65535) { // Found suitable ARR and Prescaler
            break;
        }
    }

    if (currentPrescaler > 65536 || calculatedARR <= 0) {
        // Could not find a suitable prescaler/ARR for the given frequency.
        // This might happen for extremely low or high frequencies.
        // Fallback to a default or error handling.
        MotionDriver_StopMotor(motor_id);
        return;
    }

    psc_reg = currentPrescaler - 1;
    uint32_t pulse = (calculatedARR + 1) / 2; // 50% duty cycle

    // Apply settings to the timer
    htim->Instance->PSC = psc_reg;
    htim->Instance->ARR = calculatedARR;
    __HAL_TIM_SET_COMPARE(htim, channel, pulse);

    // Start PWM generation
    HAL_TIM_PWM_Start(htim, channel);
}

/**
 * @brief Stops the PWM generation for a specific motor and disables its driver.
 * @param motor_id ID of the motor (0-7).
 */
void MotionDriver_StopMotor(uint8_t motor_id)
{
    if (motor_id >= MOTOR_COUNT) {
        return;
    }

    TIM_HandleTypeDef* htim = MotorStepTimHandles[motor_id];
    uint32_t channel = MotorStepTimChannels[motor_id];

    // Stop PWM generation
    HAL_TIM_PWM_Stop(htim, channel);

    // Disable the motor (EN is active high for disable)
    HAL_GPIO_WritePin(MotorEnPorts[motor_id], MotorEnPins[motor_id], GPIO_PIN_SET);
}

/**
 * @brief Callback function for pulse generation completion (if used, e.g., in One-Pulse mode).
 *        For continuous PWM, this typically isn't used for step completion.
 * @param htim Pointer to TIM_HandleTypeDef structure.
 */
void MotionDriver_PulseGenerationCompleted_Callback(TIM_HandleTypeDef *htim)
{
    // This callback is usually triggered by HAL_TIM_PWM_PulseFinishedCallback or similar.
    // For continuous PWM (as used for stepper STEP signals), this callback is not
    // typically relevant for indicating 'completion' of a step sequence, as PWM runs continuously.
    // It might be used if we were implementing a fixed number of pulses or one-pulse mode,
    // but not for the continuous step generation required by MotionDriver_StartMotor.
    // Keep it as a stub for now.
}
